name: 1
on:
  # pull_request:
jobs:
  node_setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
      - name: Install packages
        run: npm install