name: 3
on:
  # pull_request:
jobs:
  execute_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14'
      - name: Install packages
        run: npm install
      - name: Run Tests
        run: npm run test