name: ci
on:
  # push:
  #   branches:
  #     - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '12.16.1'
      USE_NVMRC: 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment with env
        if: env.USE_NVMRC == 'false'
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Read node version from .nvmrc
        if: env.USE_NVMRC == 'true'
        run: echo ::set-output name=NVMRC_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Setup Node.js environment with version from .nvmrc
        if: env.USE_NVMRC == 'true'
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC_VERSION }}
      - name: Install packages
        run: npm install
      - name: Execute Tests
        run: npm run test
  tag:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true