name: Notify Teams

on:
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send a Notification to Teams Channel
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
        teams_webhook_url: ${{ secrets.TEAM_HOOK }}
        message: "PR created in ${{ github.repository }} by ${{ github.actor }}.  Here is the repository url: ${{ github.server_url }}/${{ github.repository }}  Here is the PR info: ${{ github.event.pull_request.html_url }}"
