name: Notify Teams

on:
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send a Notification to Teams Channel
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
        teams_webhook_url: ${{ secrets.TEAM_HOOK }}
        message: "Pull Request created!\n\n\n\n‌‌ Author: **${{ github.actor }}**\n\n Repository: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})\n\nPull Request Link: ${{ github.event.pull_request.html_url }}"
