name: Notify Teams

on:
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send a Notification to Teams Channel
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
        teams_webhook_url: ${{ secrets.TEAM_HOOK }}
        message: "<p><h2>Pull Request created!</h2></p><p>Author: **${{ github.actor }}**</p><p>Repository: [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})</p>Pull Request Link: ${{ github.event.pull_request.html_url }}</p>"
