name: Notify Teams

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send a Notification to Teams Channel
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
        teams_webhook_url: ${{ secrets.TEAM_HOOK }}
        message: "<h1>Pull Request opened!</h1><br />Author: <strong>${{ github.actor }}</strong><br />Repository: <a href='${{ github.server_url }}/${{ github.repository }}'>${{ github.repository }}</a><br />PR: <a href='${{ github.event.pull_request.html_url }}'>${{ github.event.pull_request.title }}</a>"
