name: Notify Teams

on:
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send a Notification to Teams Channel
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
        teams_webhook_url: ${{ secrets.TEAM_HOOK }}
        message: "<h1>Pull Request created!</h1><br /><br />Author: <strong>${{ github.actor }}</strong><br />Repository: <a href='${{ github.server_url }}/${{ github.repository }}'>${{ github.repository }}</a><br />Pull Request <a href='${{ github.event.pull_request.html_url }}'>Link</a>"
